openapi: 3.0.0
paths:
  /games/match:
    post:
      operationId: createMatch
      parameters: []
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatchData"
  /games/enter-match/{code}:
    post:
      operationId: enterInMatch
      parameters: []
      responses:
        "201":
          description: ""
  /games/initial-data/{code}:
    get:
      operationId: getMap
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
  /games/match-state/{code}:
    post:
      operationId: updateMatchState
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/MatchStateUpdate"
      responses:
        "201":
          description: ""
info:
  title: Villagers
  description: Villagers is the backend for Castle Age.
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas:
    MatchData:
      type: object
      properties:
        id:
          type: number
        code:
          type: string
        active:
          type: boolean
        players:
          type: array
          items:
            type: string
        numberOfPlayers:
          type: number
        createdAt:
          format: date-time
          type: string
        updatedAt:
          format: date-time
          type: string
      required:
        - id
        - code
        - active
        - players
        - numberOfPlayers
        - createdAt
        - updatedAt
    MatchStateUpdate:
      type: object
      properties: {}
