/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/games/match': {
    post: operations['createMatch'];
  };
  '/games/enter-match/{code}': {
    post: operations['enterInMatch'];
  };
  '/games/initial-data/{code}': {
    get: operations['getMap'];
  };
  '/games/match-state/{code}': {
    post: operations['updateMatchState'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    MatchData: {
      id: number;
      code: string;
      active: boolean;
      players: string[];
      numberOfPlayers: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    MatchStatePlayerEndTurn: {
      playerId: string;
      endedTurn: boolean;
    };
    MoneyData: {
      playerId: string;
      value: number;
    };
    MatchStateUnitsMovement: {
      id: string;
      localization: string;
      playerId: string;
    };
    MatchState: {
      playersEndTurn: components['schemas']['MatchStatePlayerEndTurn'][];
      money: components['schemas']['MoneyData'][];
      turns: number;
      unitsMovement: components['schemas']['MatchStateUnitsMovement'][];
      id: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      matchId: number;
    };
    EnterInMatchResponse: {
      match: components['schemas']['MatchData'];
      matchState: components['schemas']['MatchState'];
    };
    SquareData: {
      id: string;
      type: string;
    };
    UnitMovement: {
      distance: number;
      localization: string;
    };
    UnitData: {
      id: string;
      /** @enum {string} */
      category: 'military' | 'structure';
      playerId: string;
      /** @enum {string} */
      class: 'castle' | 'gate' | 'archer' | 'spearman' | 'horseman' | 'wall';
      movement: components['schemas']['UnitMovement'];
      movementInTurn: {
        turn?: number;
        moved?: boolean;
      };
    };
    GetMapResponse: {
      rows: components['schemas']['SquareData'][][];
      units: components['schemas']['UnitData'][];
      matchState: components['schemas']['MatchState'];
    };
    MatchStateUpdate: Record<string, never>;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  createMatch: {
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['MatchData'];
        };
      };
    };
  };
  enterInMatch: {
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['EnterInMatchResponse'];
        };
      };
    };
  };
  getMap: {
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['GetMapResponse'];
        };
      };
    };
  };
  updateMatchState: {
    requestBody: {
      content: {
        'application/json': components['schemas']['MatchStateUpdate'];
      };
    };
    responses: {
      201: {
        content: never;
      };
    };
  };
}

/**
 * This is auto generated by the command g-enum, check ./package.json and ./src/add-enums-to-schema.ts into Villagers
 * Do not make direct changes to this.
 */
export enum UNITDATA_CATEGORY {
  'MILITARY' = 'military',
  'STRUCTURE' = 'structure',
}

export enum UNITDATA_CLASS {
  'CASTLE' = 'castle',
  'GATE' = 'gate',
  'ARCHER' = 'archer',
  'SPEARMAN' = 'spearman',
  'HORSEMAN' = 'horseman',
  'WALL' = 'wall',
}
