openapi: 3.0.0
paths:
  /games/match:
    post:
      operationId: createMatch
      parameters: []
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatchData"
  /games/enter-match/{code}:
    post:
      operationId: enterInMatch
      parameters: []
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MatchData"
  /games/initial-load:
    get:
      operationId: getInitialGameState
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameState"
  /games/{gameId}/state:
    post:
      operationId: updateTurn
      parameters: []
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                type: object
  /auth/login:
    post:
      operationId: signIn
      parameters: []
      responses:
        "200":
          description: ""
info:
  title: Villagers
  description: Villagers is the backend for Castle Age.
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas:
    PlayerData:
      type: object
      properties: {}
    MatchData:
      type: object
      properties:
        id:
          type: number
        code:
          type: string
        players:
          type: array
          items:
            $ref: "#/components/schemas/PlayerData"
        active:
          type: boolean
        createdAt:
          format: date-time
          type: string
        updatedAt:
          format: date-time
          type: string
      required:
        - id
        - code
        - players
        - active
        - createdAt
        - updatedAt
    MoneyData:
      type: object
      properties:
        playerId:
          type: string
        value:
          type: number
      required:
        - playerId
        - value
    UnitMovement:
      type: object
      properties:
        distance:
          type: number
        localization:
          type: string
      required:
        - distance
        - localization
    UnitData:
      type: object
      properties:
        id:
          type: string
        category:
          type: string
          enum:
            - military
            - structure
        playerId:
          type: string
        class:
          type: string
          enum:
            - castle
            - gate
            - archer
            - spearman
            - horseman
            - wall
        movement:
          $ref: "#/components/schemas/UnitMovement"
        movementInTurn:
          type: object
          properties:
            turn:
              required: true
              type: number
            moved:
              required: true
              type: boolean
      required:
        - id
        - category
        - playerId
        - class
        - movement
        - movementInTurn
    SquareData:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
      required:
        - id
        - type
    MapData:
      type: object
      properties:
        rows:
          type: array
          items:
            required: true
            type: array
            items:
              $ref: "#/components/schemas/SquareData"
      required:
        - rows
    GameState:
      type: object
      properties:
        gameId:
          type: string
        playerIds:
          type: array
          items:
            type: string
        money:
          type: array
          items:
            $ref: "#/components/schemas/MoneyData"
        turns:
          type: number
        units:
          type: array
          items:
            $ref: "#/components/schemas/UnitData"
        gameMap:
          $ref: "#/components/schemas/MapData"
      required:
        - gameId
        - playerIds
        - money
        - turns
        - units
        - gameMap
