openapi: 3.0.0
paths:
  /games/initial-load:
    get:
      operationId: getInitialGameState
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameState"
  /games/{gameId}/state:
    post:
      operationId: updateTurn
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GameState"
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameState"
info:
  title: Villagers
  description: Villagers is the backend for Castle Age.
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas:
    UnitMovement:
      type: object
      properties:
        distance:
          type: number
        localization:
          type: string
      required:
        - distance
        - localization
    UnitData:
      type: object
      properties:
        id:
          type: string
        category:
          type: string
          enum:
            - military
            - structure
        class:
          type: string
          enum:
            - castle
            - gate
            - archer
            - spearman
            - horseman
            - wall
        movement:
          $ref: "#/components/schemas/UnitMovement"
        movementInTurn:
          type: object
          properties:
            turn:
              required: true
              type: number
            moved:
              required: true
              type: boolean
      required:
        - id
        - category
        - class
        - movement
        - movementInTurn
    SquareData:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
      required:
        - id
        - type
    MapData:
      type: object
      properties:
        rows:
          type: array
          items:
            required: true
            type: array
            items:
              $ref: "#/components/schemas/SquareData"
      required:
        - rows
    GameState:
      type: object
      properties:
        gameId:
          type: string
        turns:
          type: number
        units:
          type: array
          items:
            $ref: "#/components/schemas/UnitData"
        gameMap:
          $ref: "#/components/schemas/MapData"
      required:
        - gameId
        - turns
        - units
        - gameMap
